from fastapi import APIRouter
from app.api.api_v1.endpoints import auth, products, purchases, sales, inventory, settlements, uploads, users, files, test_upload, admin, brands, categories, trending_products, warehouses, notifications, product_importer, chat, kream_scraper, adidas_accounts, feature_requests, poizon_products, naver_shopping, poizon, adidas_comparison

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["인증"])
api_router.include_router(users.router, prefix="/users", tags=["사용자"])
api_router.include_router(brands.router, prefix="/brands", tags=["브랜드"])
api_router.include_router(categories.router, prefix="/categories", tags=["카테고리"])
api_router.include_router(warehouses.router, prefix="/warehouses", tags=["창고"])
api_router.include_router(products.router, prefix="/products", tags=["상품"])
api_router.include_router(purchases.router, prefix="/purchases", tags=["구매"])
api_router.include_router(sales.router, prefix="/sales", tags=["판매"])
api_router.include_router(inventory.router, prefix="/inventory", tags=["재고"])
api_router.include_router(settlements.router, prefix="/settlements", tags=["정산"])
api_router.include_router(trending_products.router, prefix="/trending-products", tags=["인기상품"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["알림"])
api_router.include_router(chat.router, prefix="/chat", tags=["채팅"])
api_router.include_router(uploads.router, prefix="/uploads", tags=["파일 업로드"])
api_router.include_router(files.router, prefix="/files", tags=["파일"])
api_router.include_router(test_upload.router, prefix="/test-upload", tags=["테스트"])
api_router.include_router(admin.router, prefix="/admin", tags=["관리자"])
api_router.include_router(product_importer.router, prefix="/product-importer", tags=["상품수집"])
api_router.include_router(kream_scraper.router, prefix="/kream-scraper", tags=["KREAM크롤러"])
api_router.include_router(adidas_accounts.router, prefix="/adidas-accounts", tags=["아디다스계정"])
api_router.include_router(feature_requests.router, prefix="/feature-requests", tags=["요청사항"])
api_router.include_router(poizon_products.router, prefix="/poizon-products", tags=["포이즌상품"])
api_router.include_router(naver_shopping.router, prefix="/naver-shopping", tags=["네이버쇼핑"])
api_router.include_router(poizon.router, prefix="/poizon", tags=["포이즌API"])
api_router.include_router(adidas_comparison.router, prefix="/adidas-comparison", tags=["아디다스구매비교"])